### ISSUE TITLE
Where do I get the document dataset.txt？

### ISSUE THREAD

**Issue by xueweili** [smakonin/PhotonetGet#1]
Hello：
   I want to do some research about the aesthetics.I want to download the PN(Photo.net dataset) which has 3581 images.So how can I get the document dataset.txt?

**Comment by smakonin** [comment]
Use example.txt as a starting point. More info can be found in photonet_dataset_description.txt.

**Comment by xueweili** [comment]
thank you very much. I find the dataset file in http://ritendra.weebly.com/aesthetics-datasets.html
and then run your demo.Finally I got  images.

**Comment by smakonin** [comment]
Glad you were able to find them.
